cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

sudo: false

language: kotlin

matrix:
  include:
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: oraclejdk10

before_install:
 - chmod +x gradlew

install:
- true

script:
 - ./gradlew test jar

notifications:
  email: false
