cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

sudo: false

language: kotlin

jdk:
- oraclejdk8

before_install:
 - chmod +x gradlew

install:
- true

script:
 - ./gradlew test jar

notifications:
  email: false
